config/routes.rb
Rails.application.routes.draw do
  resources :games, :rules, :teams, :questions
	
	get 'menu', to: 'menu#index', as: :menu

	get 'games/:id/questions' => 'games#questions', as: :game_questions
	post 'games/:id/questions' => 'games#smart_questions'
  get 'games/:id/questions/:question' => 'games#toggle_question', as: :toggle_question
	get 'questions/:question_id/toggle_active' => 'questions#toggle_active', as: :toggle_active
	
	get 'games/:id/teams' => 'games#teams', as: :game_teams
  get 'games/:id/teams/:team' => 'games#toggle_team', as: :toggle_team

	get 'games/:id/play' => 'games#play', as: :game_play
	get 'games/:id/play/:question/:team/:answer' => 'games#play_answer', as: :game_play_answer
	get 'games/:id/play/next' => 'games#play_next', as: :game_play_next
	get 'games/:id/play/break' => 'games#play_break', as: :game_play_break
	get 'games/:id/play/scoreboard' => 'games#play_scoreboard', as: :game_play_scoreboard
	get 'games/:id/play/showQuestion' => 'games#play_show_question', as: :game_play_show_question

	get 'webhook' => 'menu#webhook', as: :game_webhook

	get 'menu/misc' => 'menu#misc', as: :menu_misc
	post 'menu/misc/deactivate' => 'menu#deactivate', as: :menu_deactivate
	post 'menu/misc/activate' => 'menu#activate', as: :menu_activate

	get 'lang/:type/:lang' => 'menu#lang', as: :lang

	root "games#game"
end

app/models/question.rb
class Question < ApplicationRecord
	validates :question, presence: true
	validates :ansA, presence: true
	validates :ansB, presence: true
	validates :ansC, presence: true
	validates :ansD, presence: true
	validates :points, presence: true
	validates :time, presence: true
	validates :justificationUrl, allow_blank: true, format: { with: %r{http[s]?:\/\/(www\.)?(.*)?\/?(.)*}i }

	has_many :game_questions
	has_many :games, through: :game_questions

	has_one :game_progress
	
	def is_all_answer(game_id)
		answers = Answer.where(
			:game_id => game_id,
			:question_id => self.id,
		)

		is_all_answers = answers.count == GameTeam.where(
			:game_id => game_id
		).count

		if answers.count > 0 && is_all_answers
			return true
		else
			return false
		end
	end

	def get_answer(answer)
		if answer.downcase == "a"
			return self.ansA
		elsif answer.downcase == "b"
			return self.ansB
		elsif answer.downcase == "c"
			return self.ansC
		elsif answer.downcase == "d"
			return self.ansD
		end
	end

	def order
		order = "abcd"

		hash = self.id.hash()

		if hash.to_s.length % 2 != 0
			hash = hash.to_s + "0"
		end

		for i in 0..hash.to_s.length-1
			i1 = i.to_i%order.length
			i2 = (i+1).to_i%order.length
			
			# swap i1 and i2
			temp = order[i1]
			order[i1] = order[i2]
			order[i2] = temp

			i += 1
		end

		return order

	end

	def count_answers(game_id, answer)
		return Answer.where(
			:game_id => game_id,
			:question_id => self.id,
			:answer => answer.upcase
		).count
	end

	def toggle_active
		self.active = !self.active
		self.save
	end

	def pretty_time
		m = self.time / 60
		s = self.time % 60

		# Add leading zero
		if s < 10
			s = "0" + s.to_s
		end

		return m.to_s + ":" + s.to_s

	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]

  # GET /questions or /questions.json
  def index
    @questions = Question.all.order(:active => :desc, :used => :asc)
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to action: "index", notice: t('succed.question.create') }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to action: 'index', notice: t('succed.question.update') }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
		@question_games = GameQuestion.where(question_id: @question.id)
		@question_game_progresses = GameProgress.where(question_id: @question.id)
		@question_answers = Answer.where(question_id: @question.id)

		if @question_games.count == 0 && @question_game_progresses.count == 0 && @question_answers.count == 0
			@question.destroy

			respond_to do |format|
				format.html { redirect_to questions_url, notice: t('succed.question.delete') }
				format.json { head :no_content }
			end
		else
			respond_to do |format|
				format.html { redirect_to questions_url, notice: t('succed.question.cannotDelete') }
				format.json { head :no_content }
			end
		end
  end

	def toggle_active
		Question.find(params[:question_id]).toggle_active

		respond_to do |format|
			format.html { redirect_to questions_path }
			format.json { head :no_content }
		end
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:question, :ansA, :ansB, :ansC, :ansD, :points, :time, :justificationUrl, :justification)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<% if question.errors.any? %>
	<div class="bg-blue-100 border-t border-b border-blue-500 text-blue-700 px-4 py-3" role="alert">
		<p class="font-bold"><%= t('toast.wrong')%></p>
			<% question.errors.each do |error| %>
				<p class="text-sm">
					<%= error.full_message %>
				</p>
			<% end %>
		</div>
	</div>
<% end %>

<%= form_with(model: question) do |form| %>
	<div class="mt-5 flex flex-col space-y-4">
		<div class="flex justify-center translate-x-5 items-center">
			<%= form.text_field :question, class: "neon-green req", placeholder: t('placeholders.questionContent') %>
			<div class="m-3">
				<%= render :partial => 'shared/tooltip', locals: {m: t('placeholders.questionContent'), req: true } %>
			</div>
		</div>

		<div class="flex justify-center translate-x-5 items-center">
			<%= form.text_field :ansA, class: "neon-green",  placeholder: t('placeholders.ansa') %>
			<div class="m-3">
				<%= render :partial => 'shared/tooltip', locals: {m: t('placeholders.ansa'), req: true } %>
			</div>
		</div>

		<div class="flex justify-center translate-x-5 items-center">
			<%= form.text_field :ansB, class: "neon-green", placeholder: t('placeholders.ansb') %>
			<div class="m-3">
				<%= render :partial => 'shared/tooltip', locals: {m: t('placeholders.ansb'), req: true } %>
			</div>
		</div>

		<div class="flex justify-center translate-x-5 items-center">
			<%= form.text_field :ansC, class: "neon-green", placeholder: t('placeholders.ansc') %>
			<div class="m-3">
				<%= render :partial => 'shared/tooltip', locals: {m: t('placeholders.ansc'), req: true } %>
			</div>
		</div>

		<div class="flex justify-center translate-x-5 items-center">
			<%= form.text_field :ansD, class: "neon-green", placeholder: t('placeholders.ansd') %>
			<div class="m-3">
				<%= render :partial => 'shared/tooltip', locals: {m: t('placeholders.ansd'), req: true } %>
			</div>
		</div>

		<div class="flex justify-center translate-x-5 items-center">
			<%= form.number_field :points, class: "neon-green", placeholder: t('placeholders.score') %>
			<div class="m-3">
				<%= render :partial => 'shared/tooltip', locals: {m: t('placeholders.score'), req: true } %>
			</div>
		</div>

		<div class="flex justify-center translate-x-5 items-center">
			<%= form.number_field :time, class: "neon-green", placeholder: t('placeholders.timeInSeconds') %>
			<div class="m-3">
				<%= render :partial => 'shared/tooltip', locals: {m: t('placeholders.timeInSeconds'), req: true } %>
			</div>
		</div>

		<div class='flex justify-center translate-x-5 items-center'>
			<%= form.text_field :justificationUrl, class: "neon-green", placeholder: t('placeholders.urlToJustification') + ' - ' + t('shared.optional') %>
			<div class="m-3">
				<%= render :partial => 'shared/tooltip', locals: {m: t('placeholders.urlToJustification') + ' - ' + t('shared.optional') } %>
			</div>
		</div>

		<div class='flex justify-center translate-x-5 items-center'>
			<%= form.text_field :justification, class: "neon-green", placeholder: t('placeholders.justification') + ' - ' + t('shared.optional') %>
			<div class="m-3">
				<%= render :partial => 'shared/tooltip', locals: {m: t('placeholders.justification') + ' - ' + t('shared.optional') } %>
			</div>
		</div>

		<div>
			<%= form.submit t('game.confirm'), class: "neon neon-green" %>
		</div>
	</div>

<% end %>

app/views/questions/edit.html.erb
<div class="row">
  <div class="col">

		<p class="text-3xl mt-5"><%= t('menu.questions.edit')%></p>
		<%= render "form", question: @question %>

    <div class="flex justify-center items-center py-8 space-x-5">
			<%= link_to t('back.toQuestion'), questions_path, class: "neon neon-gray" %>
			<%= button_to t('menu.questions.delete'), @question, method: :delete, class: "neon neon-red" %>
    </div>

  </div>
</div>

app/views/questions/index.html.erb
<%# TITLE %>
<p class="text-3xl mt-5"><%= t('menu.questions.title')%></p>

<%# TABLE %>
<% if @questions.count == 0 %>
	<p class="text-center mt-5 underline"><%= t("menu.questions.noQuestion") %></p>
<% else %>
	<div class="md:px-32 py-8 w-full">
		<div class="shadow overflow-hidden rounded border-b border-gray-200">
			<table class="min-w-full bg-white">
				<thead class="bg-gray-800 text-white">
					<tr>
						<th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">#</th>
						<th class="text-left py-3 px-4 uppercase font-semibold text-sm"><%= t('menu.questions.question')%></th>
						<th class="text-left py-3 px-4 uppercase font-semibold text-sm"><%= t('menu.questions.points')%></td>
						<th class="text-left py-3 px-4 uppercase font-semibold text-sm"><%= t('menu.game.usage')%></td>
						<th class="text-left py-3 px-4 uppercase font-semibold text-sm"><%= t('menu.questions.action')%></td>
					</tr>
				</thead>
			<tbody class="text-gray-700">

				<% @questions.each do |q| %>
					<tr>
						<td class="w-1/3 text-left py-3 px-4"><%= q.id%></td>
						<td class="w-1/3 text-left py-3 px-4"> 
							<% if uri_i?(q.question) %>
								<img src="<%= q.question %>" alt="<%= q.question %>" class="w-full h-auto">
							<% else %>
								<%= q.question %> 
							<% end %>
						</td>
						<td class="w-1/3 text-left py-3 px-4"> <%= q.points %> / <%= q.time %>s.</td>
						<td class="w-1/3 text-left py-3 px-4"><%= q.used%></td>
						<td class="text-left py-3 px-4">
							<div class="flex space-x-2">
								<%= link_to edit_question_path(q) do %>
									<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
										<path stroke-linecap="round" stroke-linejoin="round" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
										<path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
									</svg>
								<% end %>
								<% if q.active %>
									<%= link_to toggle_active_path(q.id) do %>
										<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-700" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
											<path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
											<path stroke-linecap="round" stroke-linejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
										</svg>
									<% end %>
								<% else %>
									<%= link_to toggle_active_path(q.id) do %>
										<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-red-700" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
											<path stroke-linecap="round" stroke-linejoin="round" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
										</svg>
									<% end %>

								<% end %>
							</div>
						</td>
					</tr>
				<% end %>
			</tbody>
			</table>
		</div>
	</div>
<% end %>

<%# BUTTONS %>

<div class="flex justify-center items-center py-8 space-x-5">
	<%= link_to t('menu.questions.new'), new_question_path, class: "neon neon-green"%>
	<%= link_to t('back.toMenu'), menu_path, class: "neon neon-gray"%>
</div>

app/views/questions/new.html.erb
<div class="row">
  <div class="col">

    <p class="text-3xl mt-5"><%= t('menu.questions.new')%></p>
    <%= render "form", question: @question %>

    <div class="flex justify-center items-center py-8 space-x-5">
      <%= link_to t('back.toQuestion'), questions_path, class: "neon neon-gray" %>
    </div>

  </div>
</div>

app/views/questions/test.html.erb
<h1>Widok "test"</h1>
Juz jest <%= @questions.count %> pytań<br>

<%= @tekst %>