config/routes.rb
Rails.application.routes.draw do
  resources :games, :rules, :teams, :questions
	
	get 'menu', to: 'menu#index', as: :menu

	get 'games/:id/questions' => 'games#questions', as: :game_questions
	post 'games/:id/questions' => 'games#smart_questions'
  get 'games/:id/questions/:question' => 'games#toggle_question', as: :toggle_question
	get 'questions/:question_id/toggle_active' => 'questions#toggle_active', as: :toggle_active
	
	get 'games/:id/teams' => 'games#teams', as: :game_teams
  get 'games/:id/teams/:team' => 'games#toggle_team', as: :toggle_team

	get 'games/:id/play' => 'games#play', as: :game_play
	get 'games/:id/play/:question/:team/:answer' => 'games#play_answer', as: :game_play_answer
	get 'games/:id/play/next' => 'games#play_next', as: :game_play_next
	get 'games/:id/play/break' => 'games#play_break', as: :game_play_break
	get 'games/:id/play/scoreboard' => 'games#play_scoreboard', as: :game_play_scoreboard
	get 'games/:id/play/showQuestion' => 'games#play_show_question', as: :game_play_show_question

	get 'webhook' => 'menu#webhook', as: :game_webhook

	get 'menu/misc' => 'menu#misc', as: :menu_misc
	post 'menu/misc/deactivate' => 'menu#deactivate', as: :menu_deactivate
	post 'menu/misc/activate' => 'menu#activate', as: :menu_activate

	get 'lang/:type/:lang' => 'menu#lang', as: :lang

	root "games#game"
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
	
	def deactivate
		questions = Question.where(
			used: params[:used]..,
			active: true
		)

		redirect_to menu_misc_path, notice: t('succed.question.deactivate', count: questions.count)

		questions.each do |q|
			q.active = false
			q.save
		end
	end
	
	def activate
		questions = Question.where(
			used: ..params[:used],
			active: false
		)
		c = questions.count

		questions.each do |q|
			q.active = true
			q.save
		end

		redirect_to menu_misc_path, notice: t('succed.question.activate', count: c)
	end

	def lang
		# save cookie
		cookies[:lang] = {
			value: params[:lang],
			expires: 1.year.from_now
		}

		lang = params[:lang] == 'en' ? 'English' : 'Polski'

		if params[:type] == 'admin'
			redirect_to menu_path, notice: t('succed.language.change', lang: lang)
		else
			redirect_to root_path
		end
	end

	def webhook
		render :json => {
			"count": Webhook.get_webhook_record,
			"lang": Webhook.lang
		}
	end
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/views/menu/index.html.erb
<div class="flex justify-center flex-col items-center">
	<%= image_tag 'logo.png', alt: 'icon' %>
</div>
<div class="flex justify-center flex-col items-center py-8 space-y-4">
	<%= link_to t('menu.game.title'), games_path, class: "neon neon-pink"%>
	<%= link_to t('menu.questions.title'), questions_path, class: "neon neon-green"%>
	<%= link_to t("menu.scoreboard.title"), teams_path, class: "neon neon-light-blue"%>
	<%= link_to t("menu.rules.title"), rules_path, class: "neon neon-yellow"%>
	<%= link_to t("menu.misc.title"), menu_misc_path, class: "neon neon-tail"%>
</div>

app/views/menu/misc.html.erb
<div class="container"></div>
	<div class="flex flex-col space-y-5">
		<div>
			<p class="text-3xl mt-5">
				<%= t('menu.misc.question.smartDeactivate') %>
				
					<%= form_with url: menu_deactivate_path do |form| %>
						<div class="flex flex-col justify-center items-center mt-5 space-y-3">
							<%= form.number_field :used, 
								class: "neon-red", 
								placeholder: t('misc.smart.deactivate.title'), 
								min: 1,
								:required => true 
							%>
							<%= form.submit t('misc.smart.deactivate.button'), class: "neon neon-red" %>
						</div>
					<% end %>

			</p>
		</div>
		<div>
			<p class="text-3xl mt-5">
				<%= t('menu.misc.question.smartActivate') %>
				
					<%= form_with url: menu_activate_path do |form| %>
						<div class="flex flex-col justify-center items-center mt-5 space-y-3">
							<%= form.number_field :used, 
								class: "neon-green", 
								placeholder: t('misc.smart.activate.title'), 
								:required => true 
							%>
							<%= form.submit t('misc.smart.activate.button'), class: "neon neon-green" %>
						</div>
					<% end %>

			</p>
		</div>
	</div>
</div>

<div class="flex justify-center items-center py-8 space-x-5">
	<%= link_to t('menu.questions.new'), new_question_path, class: "neon neon-green"%>
	<%= link_to t('back.toMenu'), menu_path, class: "neon neon-gray"%>
</div>