config/routes.rb
Rails.application.routes.draw do
  resources :games, :rules, :teams, :questions
	
	get 'menu', to: 'menu#index', as: :menu

	get 'games/:id/questions' => 'games#questions', as: :game_questions
	post 'games/:id/questions' => 'games#smart_questions'
  get 'games/:id/questions/:question' => 'games#toggle_question', as: :toggle_question
	get 'questions/:question_id/toggle_active' => 'questions#toggle_active', as: :toggle_active
	
	get 'games/:id/teams' => 'games#teams', as: :game_teams
  get 'games/:id/teams/:team' => 'games#toggle_team', as: :toggle_team

	get 'games/:id/play' => 'games#play', as: :game_play
	get 'games/:id/play/:question/:team/:answer' => 'games#play_answer', as: :game_play_answer
	get 'games/:id/play/next' => 'games#play_next', as: :game_play_next
	get 'games/:id/play/break' => 'games#play_break', as: :game_play_break
	get 'games/:id/play/scoreboard' => 'games#play_scoreboard', as: :game_play_scoreboard
	get 'games/:id/play/showQuestion' => 'games#play_show_question', as: :game_play_show_question

	get 'webhook' => 'menu#webhook', as: :game_webhook

	get 'menu/misc' => 'menu#misc', as: :menu_misc
	post 'menu/misc/deactivate' => 'menu#deactivate', as: :menu_deactivate
	post 'menu/misc/activate' => 'menu#activate', as: :menu_activate

	get 'lang/:type/:lang' => 'menu#lang', as: :lang

	root "games#game"
end

app/models/game.rb
class Game < ApplicationRecord
	validates :name, uniqueness: true, allow_blank: false

	has_many :game_questions
	has_many :questions, through: :game_questions

	has_many :game_teams
	has_many :teams, through: :game_teams

	has_one :game_progress

	def game_progress
		return GameProgress.where(
			:game_id => self.id,
		).where.not(
			:status => 'done'
		).first
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	before_action :set_game, only: %i[ show edit update destroy ]
	after_action :check_if_game_is_ready, only: [:toggle_question, :smart_questions, :toggle_team]

	# GET /games or /games.json
	def index
		@games = Game.all
	end

	# GET /games/new
	def new
		@game = Game.new
	end

	def check_if_game_is_ready
		# count questions and teams in game
		game_questions = GameQuestion.where(:game_id => params[:id])
		game_teams = GameTeam.where(:game_id => params[:id])

		# check if both > 0
		if @game
			if game_questions.count > 0 && game_teams.count > 1
				@game.update(:status => "ready")
			else
				@game.update(:status => "configuring")
			end
		end

		@game.save

	end

	# POST /games or /games.json
	def create
		# check if no name is given
		if params[:game][:name].empty?
			# replce with date DD-MM-YYYY
			params[:game][:name] = Date.today.strftime("%d-%m-%Y")
		end

		@game = Game.new(game_params)

		respond_to do |format|
			if @game.save
			format.html { redirect_to actions: "index", notice: t('succed.game.create') }
			format.json { render :show, status: :created, location: @game }
			else
			format.html { render :new, status: :unprocessable_entity }
			format.json { render json: @game.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /games/1 or /games/1.json
	def update
		# check if no name is given
		if params[:game][:name].empty?
			# replce with date DD-MM-YYYY
			params[:game][:name] = Date.today.strftime("%d-%m-%Y")
		end
		
		respond_to do |format|
			if @game.update(game_params)
				format.html { redirect_to games_path, notice: t('succed.game.update') }
				format.json { render :show, status: :ok, location: @game }
			else
				format.html { render :edit, status: :unprocessable_entity }
				format.json { render json: @game.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /games/1 or /games/1.json
	def destroy
		@game_questions = GameQuestion.where(:game_id => @game.id)
		@game_answers = Answer.where(:game_id => @game.id)
		@game_teams = GameTeam.where(:game_id => @game.id)
		@game_progresses = GameProgress.where(:game_id => @game.id)

		if @game_questions.count == 0 && @game_answers.count == 0 && @game_teams.count == 0 && @game_progresses.count == 0
			@game.destroy

			respond_to do |format|
				format.html { redirect_to games_path, notice: t('succed.game.delete') }
				format.json { head :no_content }
			end
		else
			respond_to do |format|
				format.html { redirect_to games_path, notice: t('succed.game.cannotelete') }
				format.json { head :no_content }
			end
		end
	end

	def questions
		@game = Game.find(params[:id])
		@name = @game.name
		@questions = Question.all.order(:used)

		if @game.status == "done" || @game.status == "running"
			redirect_to games_path, notice: t('succed.game.runned')
			return
		end

		# get all possible questions points uniq
		@points = @questions.map { |q| q.points }.uniq
	end

	def toggle_question(game_id = nil, question = nil, redirect = true)
		@game = Game.find(game_id || params[:id])
		@question = Question.find(question || params[:question])

		if @game.questions.include?(@question)
			@game.questions.delete(@question)
			@question.decrement!(:used)
		else
			@game.questions << @question
			@question.increment!(:used)
		end

		if redirect
			respond_to do |format|
				format.html { redirect_to game_questions_path(@game) }
				format.json { head :no_content }
			end
		end
	end	

	def smart_questions
		# Get question with point params[:points] and not used in this game
		@questions = Question.where(
			points: params[:points],
			active: true
		).order(:used).limit(params[:limit]).to_a

		game_id = params[:game]
		game_questions = GameQuestion.where(:game_id => game_id)
		@questions = @questions - game_questions.map { |q| q.question }

		# Add each question to game by toggle_question
		@questions.each do |question|
			toggle_question(game_id, question.id, false)
		end

		# redirect to game_questions_path
		respond_to do |format|
			format.html { redirect_to game_questions_path(game_id) }
			format.json { head :no_content }
		end
	end

	def teams
		@game_id = params[:id]
		@game = Game.find(@game_id)
		@name = @game.name
		@teams = Team.all.order(:orderID)
		
		if @game.status == "done" || @game.status == "running"
			redirect_to games_path, notice: t('succed.game.runned')
			return
		end
	end

	def toggle_team
		@game = Game.find(params[:id])
		@team = Team.find(params[:team])

		if @game.teams.include?(@team)
			@game.teams.delete(@team)
		else
			@game.teams << @team
		end

		respond_to do |format|
			format.html { redirect_to game_teams_path(@game) }
			format.json { head :no_content }
		end
	end

	def game
		@gp = GameProgress.where.not(
			:status => 'done'
		).first

		if ! @gp.nil?
			prepare_game_vars(@gp.game_id)
			
			if @gp.status == "rules"
				@rules = Rule.all().order(:orderID)
			end

		end

	end 

	def prepare_game_vars(game_id = nil)
		if ! game_id.nil?
			params[:id] = game_id
		end
		@gp = GameProgress.find_by(:game_id => params[:id])

		@question = Question.find(@gp.question_id)
		teams_id = GameTeam.where(:game_id => params[:id])
		@teams = Team.where(:id => teams_id.map { |t| t.team_id })

		questions_id = GameQuestion.where(:game_id => params[:id])
		@questions = Question.where(:id => questions_id.map { |q| q.question_id })

		@questions_done = 0
		@questions.each do |q|
			if q.is_all_answer(@gp.game_id)
				@questions_done += 1 
			end
		end
		@questions_remaining = @questions.count - @questions_done
		
		if @gp.status == "scoreboard"

			@team_scoreboard = []

			@teams.each do |team|
				team_score = team.get_score(@gp.game_id)
				@team_scoreboard.push({
					"team" => team,
					"score" => team_score
				})
			end
			# sort
			@team_scoreboard = @team_scoreboard.sort_by { |hsh| hsh[:score] }.reverse
		end
	end

	def play
		# Check if any game has status 'running'
		@games = Game.where(:status => "running")
		if @games.count > 0
			# Check if games has game with id as params[:id]
			if @games.first.id.to_i == params[:id].to_i
				# Play game (someone clicked on the running game)
				prepare_game_vars
			else
				# redirect to games_path
				redirect_to games_path, notice: t('succed.game.running')
			end
		else
			# find game with status 'ready'
			@game = Game.find(params[:id])
			@game.update(:status => "running")
			@game.save

			# Get game's questions
			@questions = GameQuestion.where(:game_id => @game.id)
			@question = @questions.first.id

			# Make new game_progress
			@game_progress = GameProgress.new(
				:game_id => @game.id, 
				:question_id => @question,
				:status => "rules"
			)
			@game_progress.save()
			add_webhook_record

			prepare_game_vars
		end
	end

	def play_answer
		# Remove old answer
		Answer.where(:game_id => params[:id], :question_id => params[:question], :team_id => params[:team]).destroy_all

		# Create new answer
		@answer = Answer.new(
			:game_id => params[:id],
			:question_id => params[:question],
			:team_id => params[:team],
			:answer => params[:answer]
		)
		@answer.save()

		# If that was the last answer send webhook
		if Question.find( params[:question] ).is_all_answer(params[:id])
			add_webhook_record			
		end

		# Redirect
		respond_to do |format|
			format.html { redirect_to game_play_path(params[:id]) }
			format.json { head :no_content }
		end
	end

	def play_next
		# Get game_progress
		gp = GameProgress.where(
			:game_id => params[:id],
		).where.not(
			:status => "done"
		)

		# Change status to play
		if gp.first.status != "play" && gp.first.status != "done"
			gp.first.update(:status => "play")
			gp.first.save()

			# Send webhook
			add_webhook_record

			# Redirect
			respond_to do |format|
				format.html { redirect_to game_play_path(params[:id]) }
				format.json { head :no_content }
			end

			return # Do not change q if that was break or scoreboard
		end
		

		if ! gp.first.get_next_question.nil?
			if Question.find(gp.first.question_id).is_all_answer(gp.first.game_id)
				gp.first.update(
					:question_id => gp.first.get_next_question
				)
				gp.first.save()

				add_webhook_record

				# Redirect
				respond_to do |format|
					format.html { redirect_to game_play_path(params[:id]) }
					format.json { head :no_content }
				end
			else
				respond_to do |format|
					format.html { redirect_to game_play_path(params[:id]), notice: t('succed.question.answer') }
					format.json { head :no_content }
				end
			end
		else
			gp.first.update(:status => "done")
			gp.first.save()

			game = Game.find(gp.first.game_id)
			game.update(:status => "finished")

			# Change teams best score
			teams_id = GameTeam.where(:game_id => params[:id])
			teams = Team.where(:id => teams_id.map { |t| t.team_id })
			teams.each do |t|
				if t.bestScore < t.get_score(params[:id])
					t.update(:bestScore => t.get_score(params[:id]))
				end
			end

			add_webhook_record

			redirect_to games_path, notice: t('succed.game.finished')
		end
	end

	def play_scoreboard
		gp = GameProgress.where(
			:game_id => params[:id],
		).where.not(
			:status => "done"
		)

		gp.first.update(:status => "scoreboard")
		gp.first.save()

		add_webhook_record

		# Redirect
		respond_to do |format|
			format.html { redirect_to game_play_path(params[:id]) }
			format.json { head :no_content }
		end
	end

	def play_break
		gp = GameProgress.where(
			:game_id => params[:id],
		).where.not(
			:status => "done"
		)

		gp.first.update(:status => "break")
		gp.first.save()

		add_webhook_record

		# Redirect
		respond_to do |format|
			format.html { redirect_to game_play_path(params[:id]) }
			format.json { head :no_content }
		end
	end

	def add_webhook_record
		# Add info to reload game root page
		Webhook.create(
			:lang => I18n.locale == :pl ? 'pl' : 'en'
		)
	end

	def play_show_question
		gp = GameProgress.where(
			:game_id => params[:id],
		).where.not(
			:status => "done"
		)

		gp.first.update(:status => "play")

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<p class="text-3xl mt-5"><%= t('menu.game.title')%></p>

<% if @games.count == 0 %>
	<p class="text-center mt-5 underline"><%= t("menu.game.noGame") %></p>
<% else %>
	<div class="md:px-32 py-8 w-full">
		<div class="shadow overflow-hidden rounded border-b border-gray-200">
			<table class="min-w-full bg-white">
				<thead class="bg-gray-800 text-white">
					<tr>
						<th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm"><%= t('menu.game.name')%></th>
						<th class="text-left py-3 px-4 uppercase font-semibold text-sm"><%= t('menu.game.status')%></th>
						<th class="text-left py-3 px-4 uppercase font-semibold text-sm"><%= t('menu.game.actions')%></td>
					</tr>
				</thead>
			<tbody class="text-gray-700">

				<% @games.each do |game| %>
					<tr>
						<td class="w-1/3 text-left py-3 px-4"><%= game.name%></td>
						<td class="w-1/3 text-left py-3 px-4"> <%= t('succed.game.status.' + game.status) %> </td>
						<td class="text-left py-3 px-4">
							<div class="flex space-x-2">
								<%= link_to edit_game_path(game), title: t('actions.rename') do %>
									<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
										<path stroke-linecap="round" stroke-linejoin="round" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
										<path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
									</svg>
								<% end %>
								<%= link_to game_questions_path(game), title: t('actions.question') do %>
									<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
										<path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 10h16M4 14h16M4 18h16" />
									</svg>
								<% end %>
								<%= link_to game_teams_path(game), title: t('actions.teams') do %>
									<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
										<path stroke-linecap="round" stroke-linejoin="round" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
									</svg>
								<% end %>

								<%# PLAY BUTTON %>
								<% if game.status == "ready" || game.status == "running" %>
									<%= link_to game_play_path(game.id) do %>
										<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
											<path stroke-linecap="round" stroke-linejoin="round" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
											<path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
										</svg>
									<% end %>
								<% else %>
									<%= link_to games_path, title: "Game is not ready!" do %>
										<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
											<path stroke-linecap="round" stroke-linejoin="round" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
											<path stroke-linecap="round" stroke-linejoin="round" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
										</svg>
									<% end %>
								<% end %>
							</div>
						</td>
					</tr>
				<% end %>
			</tbody>
			</table>
		</div>
	</div>
<% end %>

<div class="flex justify-center items-center py-8 space-x-5">
	<%= link_to t('menu.game.new'), new_game_path, class: "neon neon-green"%>
	<%= link_to t('back.toMenu'), menu_path, class: "neon neon-gray"%>
</div>

app/views/games/play.html.erb
<div class="w-10/12 flex flex-col mt-14 mx-auto">
	<%# QUESTION %>
	<div class="text-4xl border border-white p-3"> 
		<% if uri_i?(@question.question) %>
			<div class="flex justify-center">
				<img src="<%= @question.question %>" alt="">
			</div>
		<% else %>
			<%= @question.question %> 
		<% end %>
	</div>
	
	<%# time and points %>
	<div class="flex">
		<div class="w-1/2 text-center border">
			<%= @question.points %> points!
		</div>
		<div class="w-1/2 text-center border">
			<%= @question.pretty_time %>
		</div>
	</div>

	<%# ANSWERS %>
	<div class="flex flex-wrap mt-2">

		<% letters = "ABCD" %>
		<% @question.order.split('').each_with_index do |o, i| %>
			<div class="border bottom-white w-1/2">
				<% if uri_i?(@question.question) %>
					<div class="flex justify-center">
						<img src="<%= @question.get_answer(o) %>" class="w-1/2" alt="">
					</div>
				<% else %>
					<%= letters[i] %>. <%= @question.get_answer(o) %>
				<% end %>
			</div>
		<% end %>
	</div>
	
	<%# TEAMS %>
	<div class="my-4 border border-white">
		<% @teams.each do |t| %>
			<div class="flex my-2">
				<div class="w-2/3">
					<div class="font-bold p-1"><%= t.name %></div>
				</div>
				<div class="flex flex-wrap w-1/3">

					<% @question.order.split('').each_with_index do |o, i| %>
						<div class="rounded-md border border-white p-1 mx-1 <%= 'bg-orange-500' if t.get_answer(@question.id, @gp.game_id) == o.upcase %>">
							<%= link_to letters[i], game_play_answer_path(@gp.game_id, @gp.question_id, t.id, o.upcase) %>
						</div>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>

	<%# GAME PROGRESS %>
	<div class="flex border border-white p-5">
		<% for c in 1..@questions_done %>
			<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="flex-1 bi bi-circle-fill" viewBox="0 0 16 16"> <circle cx="8" cy="8" r="8"/> </svg>
		<% end %>
		<% for c in 1..@questions_remaining %>
			<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="flex-1 bi bi-circle" viewBox="0 0 16 16"> <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/> </svg>
		<% end %>
	</div>

	<%# BUTTONS %>
	<div class="flex flex-col md:flex-row justify-center items-center py-8 space-y-3 md:space-y-0 md:space-x-5">
			<%# next?, !play, rules? %>
			<% if @gp.status == "rules" %>
				<% t = t('panel.buttons.Start_the_game') %>
			<% elsif @gp.status != "play" %>
				<% t = t('panel.buttons.Return_to_game') %>
			<% elsif @gp.get_next_question %>
				<% t = t('panel.buttons.Next_question') %>
			<% else %>
				<% t = t('panel.buttons.Finish_game') %>
			<% end %>
			
			<%= link_to t, game_play_next_path(@gp.game_id), class: "neon neon-yellow"%>

			<% if uri?(@question.justificationUrl) %>
				<%= link_to "Justification", @question.justificationUrl, class: "neon neon-green", :target => "_blank" %>
			<% else %>
				<p class="neon neon-disabled">
					<%= t('panel.buttons.Justification') %>
				</p>
			<% end %>
			
			<%= link_to t('panel.buttons.Break'), game_play_break_path(@gp), class: "neon neon-light-blue"%>
			<%= link_to t('panel.buttons.Scoreboard'), game_play_scoreboard_path(@gp), class: "neon neon-pink"%>
	</div>
</div>

app/views/games/questions.html.erb
<%# HAED TITLE %>
<p class="text-3xl mt-5"><%= t('menu.game.manage', name: @name)%></p>

<%# SMART ADDING %>
<% if Question.all.count > 0 %>
	<p class="text-2xl mt-5"><%= t('menu.game.draw') %></p>

	<% @points.each do |p| %>
		<%# input for how many question with p points %>
		<%= form_with do |form| %>
			<%= form.hidden_field :points, value: p %>
			<%= form.hidden_field :game, value: @game.id %>
			<%= form.number_field :limit, class: "neon-green", placeholder: t('menu.game.numberOfQuestions', points: p), :required => true %>
			<%= form.submit t('game.confirm'), class: "neon neon-green" %>
		<% end %>

	<% end %>
<% end %>

<%# TABLE MANUAL %>
<p class="text-2xl mt-5"><%= t('menu.game.manual') %></p>

<div class="md:px-32 py-8 w-full">
	<div class="shadow overflow-hidden rounded border-b border-gray-200">
		<table class="min-w-full bg-white">
			<thead class="bg-gray-800 text-white">
				<tr>
					<th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">#</th>
					<th class="text-left py-3 px-4 uppercase font-semibold text-sm"> <%= t('menu.game.questionTitle') %> </th>
					<th class="text-left py-3 px-4 uppercase font-semibold text-sm"> <%= t('menu.game.usage') %> </td>
					<th class="text-left py-3 px-4 uppercase font-semibold text-sm"> <%= t('menu.game.points') %> </td>
					<th class="text-left py-3 px-4 uppercase font-semibold text-sm"> <%= t('menu.game.actions') %></td>
				</tr>
			</thead>
		<tbody class="text-gray-700">

			<% if Question.all.count == 0 %>
			<tr>
				<td colspan="5">
					<%= link_to "No teams questions, add some!", new_question_path, class: 'text-blue-500 underline'  %>
				</td>
			</tr>
			<% else %>
				<% @questions.each do |q| %>
					<tr>
						<td class="text-left py-3 px-4"> <%= q.id %> </td>
						<td class="text-left py-3 px-4"> <%= q.question %> </td>
						<td class="text-left py-3 px-4"> <%= q.used %> </td>
						<td class="w-1/3 text-left py-3 px-4"> <%= q.points %> / <%= q.time %>s.</td>
						<td class="text-left py-3 px-4">
							<%= link_to toggle_question_path(@game, q.id) do %>
								<% if !@game.questions.include?(q) %>
									<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
										<path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
									</svg>
								<% else %>
									<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
										<path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
									</svg>
								<% end %>
							<% end %>
						</td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
		</table>
	</div>
</div>

<%# BOTTOM BUTTONS %>
<div class="flex justify-center items-center py-8 space-x-5">
	<%= link_to t('back.toMenu'), menu_path, class: "neon neon-gray"%>
	<%= link_to t('back.toGame'), games_path, class: "neon neon-gray"%>
</div>

app/views/games/teams.html.erb
<%# HAED TITLE %>
<p class="text-3xl mt-5"><%= t('menu.game.teamTitle')%></p>

<div class="md:px-32 py-8 w-full">
	<div class="shadow overflow-hidden rounded border-b border-gray-200">
		<table class="min-w-full bg-white">
			<thead class="bg-gray-800 text-white">
				<tr>
					<th class="w-1/3 text-left py-3 px-4 uppercase font-semibold text-sm">#</th>
					<th class="text-left py-3 px-4 uppercase font-semibold text-sm"><%= t('menu.game.teamName')%></th>
					<th class="text-left py-3 px-4 uppercase font-semibold text-sm"><%= t('menu.game.teamQuantity')%></td>
					<th class="text-left py-3 px-4 uppercase font-semibold text-sm"> <%= t('menu.game.action') %></td>
				</tr>
			</thead>
		<tbody class="text-gray-700">

			<% if Team.all.count == 0 %>
			<tr>
				<td colspan="5">
					<%= link_to "No teams teams, add some!", new_team_path, class: 'text-blue-500 underline'  %>
				</td>
			</tr>
			<% else %>
				<% @teams.each do |t| %>
					<tr>
						<td class="text-left py-3 px-4"> <%= t.id %> </td>
						<td class="text-left py-3 px-4"> <%= t.name %> </td>
						<td class="w-1/3 text-left py-3 px-4"> <%= t.quantity %></td>
						<td class="text-left py-3 px-4">
							<%= link_to toggle_team_path(@game_id, t.id) do %>
								<% if !@game.teams.include?(t) %>
									<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-green-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
										<path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
									</svg>
								<% else %>
									<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-red-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
										<path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z" />
									</svg>
								<% end %>
							<% end %>
						</td>
					</tr>
				<% end %>
			<% end %>
		</tbody>
		</table>
	</div>
</div>

<%# BOTTOM BUTTONS %>
<div class="flex justify-center items-center py-8 space-x-5">
	<%= link_to t('back.toMenu'), menu_path, class: "neon neon-gray"%>
	<%= link_to t('menu.scoreboard.new'), new_team_path, class: "neon neon-green"%>
	<%= link_to t('back.toGame'), games_path, class: "neon neon-gray"%>
</div>