config/routes.rb
Rails.application.routes.draw do
  resources :games, :rules, :teams, :questions
	
	get 'menu', to: 'menu#index', as: :menu

	get 'games/:id/questions' => 'games#questions', as: :game_questions
	post 'games/:id/questions' => 'games#smart_questions'
  get 'games/:id/questions/:question' => 'games#toggle_question', as: :toggle_question
	get 'questions/:question_id/toggle_active' => 'questions#toggle_active', as: :toggle_active
	
	get 'games/:id/teams' => 'games#teams', as: :game_teams
  get 'games/:id/teams/:team' => 'games#toggle_team', as: :toggle_team

	get 'games/:id/play' => 'games#play', as: :game_play
	get 'games/:id/play/:question/:team/:answer' => 'games#play_answer', as: :game_play_answer
	get 'games/:id/play/next' => 'games#play_next', as: :game_play_next
	get 'games/:id/play/break' => 'games#play_break', as: :game_play_break
	get 'games/:id/play/scoreboard' => 'games#play_scoreboard', as: :game_play_scoreboard
	get 'games/:id/play/showQuestion' => 'games#play_show_question', as: :game_play_show_question

	get 'webhook' => 'menu#webhook', as: :game_webhook

	get 'menu/misc' => 'menu#misc', as: :menu_misc
	post 'menu/misc/deactivate' => 'menu#deactivate', as: :menu_deactivate
	post 'menu/misc/activate' => 'menu#activate', as: :menu_activate

	get 'lang/:type/:lang' => 'menu#lang', as: :lang

	root "games#game"
end

app/models/rule.rb
class Rule < ApplicationRecord
	validates :content, presence: true
	validates :orderID, presence: true
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: %i[ show edit update destroy ]

  # GET /rules or /rules.json
  def index
    @rules = Rule.all
  end

  # GET /rules/1 or /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules or /rules.json
  def create
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to action: "index", notice: t('succed.rule.create') }
        format.json { render :show, status: :created, location: @rule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1 or /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to action: "index", notice: t('succed.rule.update') }
        format.json { render :show, status: :ok, location: @rule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1 or /rules/1.json
  def destroy
    @rule.destroy

    respond_to do |format|
      format.html { redirect_to rules_url, notice: t('succed.rule.delete') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rule_params
      params.require(:rule).permit(:content, :orderID)
    end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.erb
<% if rule.errors.any? %>
		<div class="bg-blue-100 border-t border-b border-blue-500 text-blue-700 px-4 py-3" role="alert">
			<p class="font-bold"><%= t('toast.wrong') %></p>
        <% rule.errors.each do |error| %>
					<p class="text-sm">
						<%= error.full_message %>
					</p>
        <% end %>
			</div>
    </div>
  <% end %>

<%= form_with(model: rule) do |form| %>

	<div class="mt-5 flex flex-col space-y-4">
		<div class="flex justify-center translate-x-5 items-center">
			<%= form.text_field :content, class: "neon-green", placeholder: t('placeholders.ruleContent') %>
			<div class="m-3">
				<%= render :partial => 'shared/tooltip', locals: {m: t('placeholders.ruleContent'), req: true } %>
			</div>
		</div>

		<div class="flex justify-center translate-x-5 items-center">
			<%= form.number_field :orderID, class: "neon-green", placeholder: t('placeholders.orderID') %>
			<div class="m-3">
				<%= render :partial => 'shared/tooltip', locals: {m: t('placeholders.orderID'), req: true } %>
			</div>
		</div>

		<div>
			<%= form.submit t('game.confirm'), class: "neon neon-green" %>
		</div>
	</div>

<% end %>

app/views/rules/edit.html.erb
<div class="row">
  <div class="col">
		<p class="text-3xl mt-5"><%= t('menu.rules.edit')%></p>

		<%= render "form", rule: @rule %>

		<br>

		<div class="flex justify-center space-x-3">
			<%= link_to t('back.toRules'), rules_path, class: "neon neon-gray" %>
			<%= button_to t('menu.rules.delete'), @rule, method: :delete, class: "neon neon-red" %>
		</div>
	</div>
</div>

app/views/rules/index.html.erb
<p class="text-3xl mt-5"><%= t('menu.rules.title') %></p>

<ul class="list-decimal">
		<% if @rules.count == 0 %>
			<p class="text-center mt-5 underline"><%= t("menu.rules.noRules") %></p>
		<% else %>
			<% @rules.order(:orderID).each do |rule| %>
				<div class="flex justify-between">
					<%= rule.orderID %>. 
					<%= rule.content %>

					<%= link_to edit_rule_path(rule) do %>
						<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
							<path stroke-linecap="round" stroke-linejoin="round" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
							<path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
						</svg>
					<% end %>

				</div>
			<% end %>
		<% end %>

	</ul>

	<div class="flex justify-center items-center py-8 space-x-5">
		<%= link_to t('menu.rules.new'), new_rule_path, class: "neon neon-green"%>
		<%= link_to t('back.toMenu'), menu_path, class: "neon neon-gray"%>
	</div>

app/views/rules/new.html.erb
<div class="row">
  <div class="col">

    <p class="text-3xl mt-5"><%= t('menu.rules.new')%></p>
    <%= render "form", rule: @rule  %>

    <div class="flex justify-center items-center py-8 space-x-5">
      <%= link_to t('back.toRules'), rules_path, class: "neon neon-gray" %>
    </div>
  </div>
</div>